import { GetServerSideProps, NextPage } from "next"
import Head from "next/head"

import Navbar from "./navbar"

const Layout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>มอเตอร์พลัส</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main>{children}</main>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  return {
    props: {
      data: null,
    },
  }
}

export default Layout
