import { GetServerSideProps, NextPage } from "next";
import {css, jsx} from "@emotion/react"

import Head from "next/head";
import MenuAppBar from "./menu-appbar";
import Toolbar from "@mui/material/Toolbar";
import styled from "@emotion/styled"

const Layout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>มอเตอร์พลัส</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MenuAppBar />
      <main>{children}</main>
    </>
  );
};

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  return {
    props: {
      data: null,
    },
  };
};

export default Layout;

