import { GetServerSideProps, NextPage } from "next"
import { useSession } from "next-auth/react"
import Head from "next/head"

// import { ThemeProvider, createTheme } from "@mui/material"
import { ThemeProvider, createTheme } from "@mui/material/styles"

import Navbar from "./navbar"

const theme = createTheme()

const Layout: NextPage = ({ children }) => {
  return (
    <>
      <Head>
        <title>มอเตอร์พลัส</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ThemeProvider theme={theme}>
        <Navbar />
        <main>{children}</main>
      </ThemeProvider>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async (ctx) => {
  return {
    props: {
      data: null,
    },
  }
}

export default Layout
